### ISSUE TITLE
install library over pip3

### ISSUE THREAD

**Issue by tonipetrovic** [MislavMandaric/vaillant-netatmo-api#35]
Dear all,

I cannot install the lib over pip3.

I get:

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting vaillant-netatmo-api
  Could not find a version that satisfies the requirement vaillant-netatmo-api (from versions: )
No matching distribution found for vaillant-netatmo-api

Thank you and kind regards,
Toni

**Comment by MislavMandaric** [comment]
Hi @tonipetrovic.

I tried installing the library and had no issues with it.

Can you please share the command you used and the environment where you tried installing it (ie. which OS, which Docker image, etc.)?

**Comment by MislavMandaric** [comment]
Closing because there was no followup.
