### ISSUE TITLE
async_set_minor_mode

### ISSUE THREAD

**Issue by DanUytFc** [MislavMandaric/vaillant-netatmo-api#37]
I would like to disable the manual mode of the Vaillant vSMART each day at 22:00. This used to be possible with the IFTTT integration. However Vaillant decided end of last year to stop this interface. 

The idea is to use a Raspberry Pi with Python 3 and your provided python solution. 

I have installed the vaillant-netatmo-api successfully. 

The source code to access the Thermostat API gives a runtime error "SyntaxError: 'async with' outside async function". Most likely there is an issue with the python script I want to execute. 

Would it be possible to provide a working python script to access the Thermostat API in order to disable the manual mode. 

Thanks in advance, Daniel

**Comment by MislavMandaric** [comment]
Hey @DanUytFc.

Can you share the script you tried executing? Please remove any personal or sensitive information (like emails, passwords or tokens) before sharing.

There is a basic example in the `example.py` file in the root of the repository. Maybe that can help you out getting started.

**Comment by DanUytFc** [comment]
Hello Mislav, 

Great to get in touch with you. 

The script I executed was a copy/paste of the code provided in the README to access the Thermostat API. Most likely the error I get while executing is because I have to add code to get a correct python script. I has been a while since I worked with Python.

from vaillant_netatmo_api import thermostat_client, SystemMode, Token

CLIENT_ID = ""
CLIENT_SECRET = ""

token_string = read_from_storage()
token = Token.deserialize(token_string)

def handle_token_update(token):
    token_string = token.serialize()
    write_to_storage(token_string)

async with thermostat_client(CLIENT_ID, CLIENT_SECRET, token, handle_token_update) as client:
    devices = await client.async_get_thermostats_data()

    d_id = devices[0].id
    m_id = devices[0].modules[0].id

    await client.async_set_system_mode(d_id, m_id, SystemMode.WINTER)

I also executed the example.py code. The first execution error was because the “load_dotenv()” was not found. I installed "pip install python-dotenv”. Now I get the following execution error "ModuleNotFoundError: No module named ‘src’”. 
I did not change any of the id’s below. If so, which values do I have to use? I have only have a username/passwd which I use in the vSmart App on my iPhone. 

client_id = os.environ['CLIENT_ID']
client_secret = os.environ['CLIENT_SECRET']
username = os.environ['USERNAME']
password = os.environ['PASSWORD']
user_prefix = os.environ['USER_PREFIX']
app_version = os.environ['APP_VERSION']


Groeten, Daniel Uyttenhove

**Comment by DanUytFc** [comment]
Mislav, 

Finally I was able to figure out the CLIENT_SECRET to make the 'https://app.netatmo.net/oauth2/token' authentication work. 

Issue can be closed. 

Below the python3 draft code where 'my_client_secret', 'my@mail.com', 'mypassword' needs to be replaced with the correct credentials. 

import requests, json
from datetime import timedelta
# Netatmo vSmart authentication
url = 'https://app.netatmo.net/oauth2/token'
messageBody = {
            	"app_version": '1.0.0.22',
            	"grant_type": 'password',
            	"client_id": 'na_client_android_vaillant',
            	"client_secret": 'my_client_secret',
            	"username": 'my@mail.com',
            	"password": 'mypassword',
            	"user_prefix": 'vaillant',
              }

apiResponse = requests.post(url, data = messageBody)
if not apiResponse.ok:
	print('Netatmo Connect oauh2 API returned: %s' % (apiResponse.status_code))
	exit(1)

vSmart = json.loads(apiResponse.text)
accessToken = vSmart["access_token"]
refreshToken = vSmart["refresh_token"]
expiresIn = vSmart["expires_in"]
print('refresh_token: %s' % (refreshToken))
print('expires_in: %s' % (timedelta(seconds=expiresIn)))
print('access_token: %s' % (accessToken))
