### ISSUE TITLE
Parameters to authenticate / Understand the process

### ISSUE THREAD

**Issue by marco-dea** [MislavMandaric/vaillant-netatmo-api#40]
Hi @MislavMandaric 
Thanks for creating this package.

I have a Migo/Smart thermo and I'd like to write a simple python program to read its data and store them into a Google spreadsheet.
I've already done it for a Tado thermo.

I'd like to use your package, but I've only username and password of Migo/Smart and I don't understand where to find the parameters for the authentication (ie  user_prefix, app_version, CLIENT_ID, CLIENT_SECRET).

Have you any advice or documents?
This is not a feature request but I don't know the way to request your support

Kind regards

**Comment by MislavMandaric** [comment]
Hey.

Check out [this thread](https://community.home-assistant.io/t/added-support-for-vaillant-thermostat-how-to-integrate-in-official-release/31858) for getting the parameters.
